In [1]:
import numpy as np
import pandas as pd

In [81]:
for i in range(3):
    for j in range (3):
        for k in range(3):
            print(i,j,k)

0 0 0
0 0 1
0 0 2
0 1 0
0 1 1
0 1 2
0 2 0
0 2 1
0 2 2
1 0 0
1 0 1
1 0 2
1 1 0
1 1 1
1 1 2
1 2 0
1 2 1
1 2 2
2 0 0
2 0 1
2 0 2
2 1 0
2 1 1
2 1 2
2 2 0
2 2 1
2 2 2


# Matrix Multiplication

In [78]:
M1 = [[8, 14, -6], 
      [12,7,4], 
      [-11,3,21]]

M2 = [[3, 16, -6],
           [9,7,-4], 
           [-1,3,13]]

M3  = [[0,0,0],
       [0,0,0],
       [0,0,0]]

matrix_length = len(M1)

#To Multiply M1 and M2 matrices
#if M1.shape[1] == M2.shape[0]:
for i in range(len(M1)):
    for j in range (len(M2)):
        for k in range(len(M3)):
            M3[i][j] += M1[i][k] * M2[k][j]

#To Print the matrix
print("The multiplication of Matrix M1 and M2 = ", M3)

m11 = np.array(M1)
m22 = np.array(M2)

m33 = m11.dot(m22)

print(m33)

The multiplication of Matrix M1 and M2 =  [[156, 208, -182], [95, 253, -48], [-27, -92, 327]]
[[ 156  208 -182]
 [  95  253  -48]
 [ -27  -92  327]]


In [79]:
(M1[0][0]*M2[0][0]) + (M1[0][1]*M2[1][0]) +(M1[0][2]*M2[2][0])
#m11

156

In [80]:
m33[0][0]

156

In [47]:
mat1 = [[1, 6, 5],[3 ,4, 8]]
mat2 = [[3, 4, 6],[5, 6, 7],[6,56, 7]]
 
# This will return dot product
res = np.dot(mat1,mat2)
res

array([[ 63, 320,  83],
       [ 77, 484, 102]])

In [48]:
mat1 = [[3,2],[2 ,3],[3,4]]
mat2 = [[1,0],[0,1]]
 
# This will return dot product
res = np.dot(mat1,mat2)
res

array([[3, 2],
       [2, 3],
       [3, 4]])

In [7]:
mat1 = [[1, 2, 3],[1 ,2, 2]]
mat2 = [[1, 2, 3],[1, 2, 3],[1,2,3]]
 
# This will return dot product
res = np.dot(mat1,mat2)
res

array([[ 6, 12, 18],
       [ 5, 10, 15]])

In [92]:
M1 = [[8, 14, -6],
           [12,7,4], 
           [-11,3,21]]

matrix_length = len(M1)

#To read the last element from each row.
for i in range(matrix_length):
    print(M1[i][2])
    


-6
4
21


In [96]:
m11 = np.array(M1)
m11[:,2]

array([-6,  4, 21])

# Matrix Transpose

In [97]:
M1 = np.array([[3, 6, 9], [5, -10, 15], [4,8,12]])
M2 = M1.T
M2

array([[  3,   5,   4],
       [  6, -10,   8],
       [  9,  15,  12]])

In [100]:
M1.shape[1]

3

# Matrix Slicing

In [12]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]

my_array1 = np.array(list2)
print(my_array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
my_array1[1,2]

6

In [11]:
#Print all rows and the third column data.

M1 = np.array([[2, 4, 6, 8, 10], 
    [3, 6, 9, -12, -15],
    [4, 8, 12, 16, -20],
    [5, -10, 15, -20, 25]])

print(M1[:,3]) 

[  8 -12  16 -20]


# Eigen Values , Eigen Vectors and Determinant

In [30]:
import numpy as np
  
# create numpy 2d-array
m = np.array([[3, 2],
              [3, -2]])
  
print("Printing the Original square array:\n",
      m)
  
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)
  
# printing eigen values
print("Printing the Eigen values of the given square array:\n",
      w)
  
# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",
      v)

Printing the Original square array:
 [[ 3  2]
 [ 3 -2]]
Printing the Eigen values of the given square array:
 [ 4. -3.]
Printing Right eigenvectors of the given square array:
 [[ 0.89442719 -0.31622777]
 [ 0.4472136   0.9486833 ]]


In [101]:
n_array = np.array([[50, 29], [30, 44]])
  
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330
