In [9]:
import numpy as np
import pandas as pd

In [10]:
list1 = [1,2,3,4,5]

my_array = np.array(list1)
my_array

array([1, 2, 3, 4, 5])

In [11]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]

my_array1 = np.array(list2)
print(my_array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
my_array1.sum()

45

In [14]:
np.power(my_array,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [16]:
my_array

array([1, 2, 3, 4, 5])

In [18]:
a = [i**2 for i in list1]
print(a)

[1, 4, 9, 16, 25]


# Indexing in Array

In [19]:
print(list1[1])

2


In [20]:
my_array[1]

2

In [21]:
my_array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
my_array1[1]

array([4, 5, 6])

In [23]:
my_array1[1][1]

5

# Slicing in array

In [24]:
list1[1:]

[2, 3, 4, 5]

In [25]:
my_array[1:]

array([2, 3, 4, 5])

In [27]:
my_array1[1, 1:]

array([5, 6])

# Arithmetic Operations

In [42]:
my_array2 = np.array([1,2,3,4,5])

In [43]:
my_array3 = my_array + my_array2
print(my_array3)

[ 2  4  6  8 10]


In [37]:
my_array3 = my_array1 * 2

In [38]:
my_array3

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

# Concatenation in array

In [39]:
arr1 = np.array([[2,3],[4,5]])
arr2 = np.array([[6,7],[8,9]])
arr1

array([[2, 3],
       [4, 5]])

In [46]:
arr3 = np.concatenate((arr1, arr2), axis =0) #Action on rows
arr3

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
arr3 = np.concatenate((arr1, arr2), axis = 1) #Action on Columns
arr3

array([[2, 3, 6, 7],
       [4, 5, 8, 9]])

In [52]:
G=["2022-09-03"]
a = str(G[0])
print(a[5:7])

09


In [50]:
g = '2022-09-03'
g[5:7]

'09'

In [ ]:
suryanshishirish@gmail.com

a = suryanshishirish
b = gmail.com